# Converting png to pdf (screenshot format, date and time used as name:)

In [1]:
import re
from PIL import Image
import os


os.chdir('/home/nishant/pro_nis/python_codes/one_fourth_labs/other_review_materials/slides/')
!mv /home/nishant/Pictures/*.png /home/nishant/pro_nis/python_codes/one_fourth_labs/other_review_materials/slides/

for i in os.listdir():
    x=re.sub('([A-Za-z.-])','',i)
    first_part=x.split()[0]
    second_part=x.split()[1]
    x= (first_part+second_part)
    os.rename(i,x)

sorted_names=list(map(lambda x: int(x), os.listdir())) #converting to integer to sort
sorted_names=sorted(sorted_names)  #sorted
sorted_names= list(map(lambda x: str(x),os.listdir())) #converting back to string, as Image.open need string

for i in sorted_names:
    im= Image.open(i)
    if im.mode=="RGBA":
        im= im.convert('RGB')
    new_filename= str(i)+'.pdf'
    im.save(new_filename,"PDF",resolution=100.0)
    os.remove(i)

!pdfunite *.pdf /home/nishant/pro_nis/python_codes/one_fourth_labs/other_review_materials/slides_final/50_sigmoid_summary.pdf
!rm /home/nishant/pro_nis/python_codes/one_fourth_labs/other_review_materials/slides/*.pdf


# Convert all png files to pdf and join them (images are numbered as 1,2,3,4, 35 etc...)

In [239]:
from PIL import Image
import os
os.chdir('/home/nishant/pro_nis/python_codes/one_fourth_labs/other_review_materials/slides/')
!mv /home/nishant/Pictures/*.png /home/nishant/pro_nis/python_codes/one_fourth_labs/other_review_materials/slides/
for i in os.listdir():
    im= Image.open(i)
    if im.mode=="RGBA":
        im= im.convert('RGB')
    new_filename= str(f"{int(i.split('.')[0]):03}")+'.pdf'
    im.save(new_filename,"PDF",resolution=100.0)
    os.remove(i)

!pdfunite *.pdf /home/nishant/pro_nis/python_codes/one_fourth_labs/other_review_materials/slides_final/38_sigmoid_intro.pdf
!rm /home/nishant/pro_nis/python_codes/one_fourth_labs/other_review_materials/slides/*.pdf

# Random exercies from one-fourth-lab session.

___

In [85]:
import numpy as np

y= np.array([1,2,2.64,3.16,3.6,4,4.35,4.69,5])
f= np.array([1.04,2.04,2.70,3.22,3.67,4.07,4.44,4.77,4.88])

print(np.sum(np.square(y-f)))

0.04910000000000007


In [12]:
import numpy as np
np.linalg.norm([1,-1,3])

3.3166247903554

In [23]:
a= np.array([1.5, 2.5, 3.5])
b= np.array([0.9, 1.5, 2.1])

a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))

0.9999999999999999

In [25]:
np.linalg.norm([4,2,4])

6.0

In [33]:
a= np.array([1, 3, 7])
b= np.array([-1.7, -5.1, -11.9])

np.degrees(np.arccos(a.dot(b)/(np.linalg.norm(a)*np.linalg.norm(b))))

90.0

___

**Q.** [A little tough Q so don't worry if you are not able to answer this] Consider a 3 x 3 matrix A such that *all its columns are unit vectors.* Let A_ij be the element in the i-th row and the j-th column of A. Let B be the transpose of this matrix such that B_ij = A_ji. State whether the following is True of False: if C = BA then C_ij is the cosine of the angle between the i-th column of A and the j-th column of A ?

**Ans:**_Create a random matrix_

In [1]:
import numpy as np
np.random.seed(22)
A= np.random.randint(1,10,(3,3)).astype(np.float)
A

array([[6., 5., 1.],
       [5., 7., 7.],
       [5., 9., 5.]])

_Make this matrix a unit length matrix_

In [2]:
for i in range(A.shape[1]):
    A[:,i]=A[:,i]/np.linalg.norm(A[:,i])
print(A)

[[0.64699664 0.40160966 0.11547005]
 [0.53916387 0.56225353 0.80829038]
 [0.53916387 0.7228974  0.57735027]]


_The C matrix_

In [3]:
B= A.T
C= B@A
C

array([[1.        , 0.95274704, 0.8217961 ],
       [0.95274704, 1.        , 0.91820301],
       [0.8217961 , 0.91820301, 1.        ]])

_Function to generate cos of angle between each column of the matrix_

In [6]:
result_angles= np.eye(3)
def cos_angle_between_vectors(mat):
    for i in range(mat.shape[0]):
        for j in range(mat.shape[1]):
            result_angles[i,j]= np.dot(mat[:,i],mat[:,j])/(np.linalg.norm(mat[:,i])*np.linalg.norm(mat[:,j]))
    return result_angles

In [7]:
cos_angle_between_vectors(A)

array([[1.        , 0.95274704, 0.8217961 ],
       [0.95274704, 1.        , 0.91820301],
       [0.8217961 , 0.91820301, 1.        ]])

_This matches C matrix_

**Consider the logistic function as explained in the lectures f(x) = 1 / (1 + e^-(wx + b)). Compute the value of f(x) when x = 1, w =0.5 and b =1.2**

___

**Q.** Consider the logistic function as explained in the lectures f(x) = 1 / (1 + e^-(wx + b)). Compute the value of f(x) when x = 1, w =0.5 and b =1.2 

In [5]:
import numpy as np
import scipy as sp

sp.special.expit((0.5*1+1.2))

0.8455347349164652

OR

In [6]:
def logestic_function(x,w,b):
    return 1/(1+np.e**-(w*x+b))

print(logestic_function(1,0.5,1.2))

0.8455347349164652


___

Q. **Consider the following (x,y) pairs given as training data:**

x = 3, y = 0.268

x = 4, y = 0.73

x = 5, y = 0.952

x = 6, y = 0.994

x = 8, y = 0.999 

You decide to approximate the relation between x and y using the sigmoid function that we discussed in the lectures: f(x) = 1 / (1 + e^-(wx + b)). Compute the average loss made by the model when w = 0, b = 0 

In [22]:
y_hat= np.full((5),0.5)

y= np.array([0.268,0.73,0.952,0.994,0.999])

answer= np.sum(np.square(y-y_hat))/np.shape(y)[0]
print(answer)

0.160813


In [29]:
 abs((8+12*0.001)- ((2.001)**3))

6.0009999973686945e-06

___

**Q.** Consider the following (x,y) pairs given as test data:

x = 3, y = 0.268

x = 4, y = 0.73

x = 5, y = 0.952

x = 6, y = 0.994

x = 8, y = 0.999 

You decide to approximate the relation between x and y using the sigmoid function that we discussed in the lectures: f(x) = 1 / (1 + e^-(wx + b)). Suppose the parameters that you learned from the training data were w = 3, b = -2. Find the root mean square error of the model on the above test data (Select the option which is closest to the answer that you get).

In [24]:
import numpy as np

def squared_error(x,y,w,b):
    y_hat= 1/(1+np.exp(-(w.T*x+b)))
    return ( np.square(y-y_hat))

def root_mean_square(n):
    return (np.sqrt((1/n)*np.sum(squared_error(x,y,w,b))))

w= np.full((5,1),3)
b= -2
x= np.array([3,4,5,6,8])
y= np.array([0.268,0.73,0.952,0.994,0.999])

root_mean_square(5)

0.34920117982061655

___

In [26]:
l1= pd.Series([2,2,2,2])

In [28]:
(l1-l1.min())/(l1.max()-l1.min())

0   NaN
1   NaN
2   NaN
3   NaN
dtype: float64