# File Handling

In [21]:
## File I/O 
"""To read a file’s contents, call f.read(size), which reads some quantity of data and returns it as 
a string (in text mode) or bytes object (in binary mode). size is an optional numeric argument.When size is
omitted or negative, the entire contents of the file will be read and returned;

f.readline() reads a single line from the file; a newline character (\n) is left at the end of the string,
and is only omitted on the last line of the file if the file doesn’t end in a newline.

If you want to read all the lines of a file in a list you can also use list(f) or f.readlines()."""


!ls
f= open('story.txt')
print(f)
print(f.read())## next time if i try to read this file,it won't show anything, because, the cursor is at the end
print(f.read())


# to move the cursor, we use seek:
f.seek(0)
print(f.read(12)) # only 12 characters are read here. (size= 12)
## since the file is not closed, whatever changes we make in it, gets updated.
# !subl story.txt
f.seek(0)
print(f.readline())  ## readline reads one line at a time.

# to read all the entire file as, use realdlines():
print(f.readlines())  ## note, only last 2 lines are read because we have put the cursor at the end of the first line

# it's good to always close the file at the end:
print(f.closed) # here the file is not closed. So, 'closed' method returns false
f.close()
print(f.closed) #here the file is closed. So, 'closed' return true

addition.py	 file2.py	  python_bootcamp_part_1.ipynb	subtract.py
corey_oop.ipynb  first.py	  python_bootcamp_part_2.ipynb
deleteme.py	 output_51_0.png  story.txt
file1.py	 __pycache__	  story.txt~
<_io.TextIOWrapper name='story.txt' mode='r' encoding='UTF-8'>
This short story is really short.
Now, it's a bit longer than that.
the end.

This short s
This short story is really short.

["Now, it's a bit longer than that.\n", 'the end.']
False
True


In [27]:
# We use 'with open' mostly which closes file at the end:

with open('story.txt') as file:
    data = file.read()  # saves the content of the file read, which stays after the file is closed

print(file.closed)
print(data)

# in the background, 'file.__enter__()' is called for opening with 'with'
# in the background, 'file.__exit__()' is called no matter what is next while calling with 'with'
# thus we can make our own objects that can work with the 'with' statement as long as they have '__enter__' and '__exit__' method on them


True
This short story is really short.
Now, it's a bit longer than that.
the end.


In [1]:
## writing to files
# the default mode in which 'open' opens the file is 'r' i.e. read.

with open('story_new.txt','w') as file:
    file.write('This file was not present initially\n')
    file.write('It is created first and then opened for writing into it.\n\n')
    file.write('*'* 120)

!subl story_new.txt

In [2]:
## File Modes

# write mode deletes what was existing in the file and writes again. To append we use 'a' mode

with open('story_new.txt','a') as file:
    file.write("\nthis is going to get appended to the file generated in the previous block\n")
    file.write('*'*120)
    

# note that writing is done, but cursor is not seekable. we can't use 'seek'. it's always at the end.
## to overcome this limitation, we can use 'r+'

with open('story_new.txt','r+') as file:
    # unlike 'a' which appends at the end, 'r+' mode appends at the beginning.
    
    file.write('hello nishant\n') #comes at the beginning
    file.seek(10) #seeks the 10th character
    file.write(':) \n') # writes from the 10th character
    
# unlike 'a' and 'w' modes, which creates file if they are not present, 'r+' doesn't create new file.
!subl story_new.txt

* The default encoding is platform dependent. In windows, it is 'cp1252' but 'utf-8' in Linux.

So, we must not also rely on the default encoding or else our code will behave differently in different platforms.

Hence, when working with files in text mode, it is highly recommended to specify the encoding type.

f = open("test.txt",mode = 'r',encoding = 'utf-8')

In [2]:
## Binary files reading
with open('output_51_0.png','rb') as file:
    data= file.read()
# print(data)

In [20]:
from csv import reader
with open('C2ImportCalEventSample.csv') as file:
    csv_data= reader(file)  # Note: the csv_data is an iterable.
    # this data can be converted to list by:
    # print(list(csv_data))
    for i in csv_data:
        # each row is a list.
        print(f'{i[0:3]}')

print(csv_data)


['Start Date ', 'Start Time', 'End Date']
['9/5/2011', '3:00:00 PM', '9/5/2011']
['9/5/2011', '6:00:00 PM', '9/5/2011']


#### Note: reader module returns a line of input for each iteration, such as a file object or a list.

In [2]:
from csv import DictReader
with open('C2ImportCalEventSample.csv') as file:
    csv_data= DictReader(file)
    for i in csv_data:
        # each row is an Ordered dictionary
        print(i['Start Date '])
        


9/5/2011
9/5/2011


---
#### If a file is separated by some other delimiter ( say '|'), we can use :
> #### **csv_data= DictReader( file, delimiter='|')**
---

In [47]:
## Writing to csv file from a csv file example:

## with nested with statements (say uppercase all the values)


# from csv import reader, writer
# with open('C2ImportCalEventSample.csv') as file:
#     csv_reader= reader(file)
#     with open('C2ImportCalEventSample_write.csv','w') as file:
#         csv_writer= writer(file)
#         for row in csv_reader:
#             csv_writer.writerow([i.upper() for i in row ])


## with separate read and write statements:

from csv import reader, writer
with open('C2ImportCalEventSample.csv') as file:
    csv_reader= reader(file)
    data_to_write= [[i.upper() for i in row] for row in csv_reader]
#     data_to_write= [i.upper() for row in csv_reader for i in row] # this will be incorrect approach here

with open('C2ImportCalEventSample_write.csv','w') as file:
    csv_writer = writer(file)
    
#     for i in data_to_write:
#         csv_writer.writerow(i)

    csv_writer.writerows(data_to_write)
  
    

#### jupyter lab as of now don't allow including external images.

In [3]:
## writing somethig as csv

from csv import writer
with open('new_csv_file.csv','w') as file:
    write_obj= writer(file)
    write_obj.writerow(['greet','name'])
    write_obj.writerow(['hello','nishant'])
    write_obj.writerow(['bye','niki'])

### writing using DictWriter

* #### Ditwriter creates a writer object for writing using dictionaries
* #### *fieldnames* - kwargs for the DictWriter specifying headers
* #### *writeheader* - method on writer to write header row
* #### *writerow* - method on a writer to write a row based on a dictionary

In [29]:
from csv import writer, DictWriter

with open ('new_csv_file2.csv','w') as file:
    header=['Name','Breed','Age(in year)']
    write_obj= DictWriter(file,fieldnames=header)
    write_obj.writeheader()
    write_obj.writerow({
        'Breed':'rodent',
        'Name':'musak',
        'Age(in year)':3   
    })
    write_obj.writerow({
        'Breed':'rodent',
        'Name':'musak',
        'Age(in year)':5   
    })
    write_obj.writerow({
        'Breed':'rodent',
        'Name':'musak',
        'Age(in year)':8   
    })

In [39]:
## reading as dictionary and writing as dictionary

from csv import DictReader, DictWriter

def year_to_months(age):
    return float(age)*12

with open('new_csv_file2.csv') as file:
    read_obj= DictReader(file)
    file_to_write=list(read_obj)
    
with open('new_csv_file3.csv','w') as file:
    headers=['Name','Breed','Age(in months)']
    write_obj= DictWriter(file,fieldnames=headers)
    write_obj.writeheader()
    for f in file_to_write:
        write_obj.writerow({
            'Name': f['Name'],
            'Breed': f['Breed'],
            'Age(in months)': year_to_months(f['Age(in year)'])  # note: since the header is changed
                                                                #for 'Age', therefore name should 
                                                                # be mached; else, we could do f
        })
        
######### Another way of doing the same, if the headers matches ###########
        
# from csv import DictReader, DictWriter

# def year_to_months(age):
#     return float(age)*12

# with open('new_csv_file2.csv') as file:
#     read_obj= DictReader(file)
#     file_to_write=list(read_obj)
#     for i in file_to_write:
#         i['Age(in year)']= year_to_months(i['Age(in year)'])

# with open('new_csv_file3.csv','w') as file:
#     headers=['Name','Breed','Age(in year)']
#     write_obj= DictWriter(file,fieldnames=headers)
#     write_obj.writeheader()
#     for f in file_to_write:
#         write_obj.writerow(f)

---
## numpy (small intro)
---

In [12]:
import numpy as np

print(np.__version__)
my_list=[12,0,-17,1]
numpy_array_from_list= np.array(my_list)  # converting python datatype to numpy array
print()

my_tuple= (21, 2.33, 1+3j) 
numpy_array_from_my_tuple= np.array(my_tuple) #note: numpy only allows similar data type.
print(numpy_array_from_tuple) #thus, it promotes all the tuple content into complex numbers.
print()

# thus, if there is a string inside, all will be converted into string.
my_tuple2= (12, 3.33, 2+3j,'a')
numpy_array_from_my_tuple2= np.array(my_tuple2)
print(numpy_array_from_my_tuple2)
print()

print(my_tuple*5)  #replicates the tuple 5 times
print(numpy_array_from_my_tuple*5)  #multiplies each element by 5

1.14.3

[21.  +0.j  2.33+0.j  1.  +3.j]

['12' '3.33' '(2+3j)' 'a']

(21, 2.33, (1+3j), 21, 2.33, (1+3j), 21, 2.33, (1+3j), 21, 2.33, (1+3j), 21, 2.33, (1+3j))
[105.   +0.j  11.65 +0.j   5.  +15.j]


#### **numpy arange**

In [24]:
print(np.arange(12)) # almost similar to the range function in python

# to know about the size of elements, we use, .size attribute
print(np.arange(3.9,12,0.5).size)
print(len(np.arange(3.9,12,0.5))) # len gives the same result.



[ 0  1  2  3  4  5  6  7  8  9 10 11]
17
17


---
#### **linspace(), zeros(), ones(), and NumPy data types**
---

##### **linspace()**

In [34]:
## note that linspace INCLUEDS LAST VALUE

np.linspace(1,2) #creates linearly spaced array, starting and ending value is to be provided 
                 # by default, linspace creates 50 samples. the step size can be returned by 'retstep'
    
np.linspace(1,2,retstep=True)
np.linspace(1,4,3,retstep=True)  # number of samples is provided to be 3

(array([1. , 2.5, 4. ]), 1.5)

##### **zeros()**

In [45]:
print(np.zeros(4))  # note how 'zeros' function return the floating point value, unlike the arange 
print(np.zeros((3,2))) # 3x2 zero matrix is created

[0. 0. 0. 0.]
[[0. 0.]
 [0. 0.]
 [0. 0.]]


##### **ones()**

In [48]:
print(np.ones(4))
print(np.ones((3,2)))  # works similar to zeros()

[1. 1. 1. 1.]
[[1. 1.]
 [1. 1.]
 [1. 1.]]


In [50]:
## three dimensional array

print(np.ones((3,4,5))) #first value says, we have 3 2D arrays, second value says, we have 4 group of 
                        # matrices and the last parameter tells us, that each one of these arrays 
                        # contains 5 columns.
        
#similarly:
# print(np.ones((2,3,4,5)))

[[[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]

 [[1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]
  [1. 1. 1. 1. 1.]]]


##### **NumPy Datatypes**

In [54]:
# 'arange' and 'linspace' returns default 'int' data type.
# 'ones' and 'zeros' return default 'float' data type.

np.zeros(11,dtype='int64')

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

In [58]:
#the arrays mentioned uptil now are taken from the class ndarray. The attributes such as size are
# available in the class ndarray.

z=np.array([1,2,3])
print(type(z))

<class 'numpy.ndarray'>


##### **Slice arrays**

In [34]:
import numpy as np
my_array = np.arange(12) # will have 12 values (size=12)
print(my_array,'\n')
my_array.shape = (4,3)  # will be 4x3 dimentional
print(my_array,'\n') 

print(my_array[1],'\n')      # returns the second row
print(my_array[2,2],'\n')    # returns the third row, third column value
print(my_array[1][2],'\n')   # another way of accessing the value (however, don't use this way)

my_array[1][2]= 24.3  # Note: an attempt to include float value converts it to intger before adding

print(my_array,'\n')
print(my_array[2:],'\n')          # gives values third row onwards
print(my_array[1:],'\n')
print(my_array[:,1:2],'\n')
print(my_array[1:,1:2])         # first slice takes all rows except 1st. 2nd slice takes second column


[ 0  1  2  3  4  5  6  7  8  9 10 11] 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 

[3 4 5] 

8 

5 

[[ 0  1  2]
 [ 3  4 24]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 6  7  8]
 [ 9 10 11]] 

[[ 3  4 24]
 [ 6  7  8]
 [ 9 10 11]] 

[[ 1]
 [ 4]
 [ 7]
 [10]] 

[[ 4]
 [ 7]
 [10]]


#### **Boolean Mask Array**

In [53]:
# Method 1, python way

import numpy as np
my_vector=np.array([-17,-4,0,2,21,37,105])
print(my_vector)

mask_divisible_seven= 0 == my_vector%7  # note, first the evaluation happens, then assignment.
                                        # my_vector%7 == 0 returns true and false, which is assigned

print(mask_divisible_seven)
print(my_vector[mask_divisible_seven]) # returns the values that are True

sub_array=my_vector[mask_divisible_seven]
print(sub_array[sub_array>0])

[-17  -4   0   2  21  37 105]
[False False  True False  True False  True]
[  0  21 105]
[ 21 105]


In [56]:
# Method 2, numpy way

mod_test= 0 == my_vector%7
positive_test= my_vector>0
print(positive_test)   # note 0 is neither positive nor negative

combined_mask= np.logical_and(mod_test,positive_test)
print(combined_mask)
print(my_vector[combined_mask])

#### When dealing with very large arrays, the numpy logical_and module is more efficient

[False False False  True  True  True  True]
[False False False False  True False  True]
[ 21 105]


### Interruption: Youtube video content
[Numpy Broadcasting (loosing your loops)](https://www.youtube.com/watch?v=EEUXKG97YRw)

##### Try to use as less loops as possible in python. Python does something called type checking all the time, which makes it slower than languages like fortran and C. This type checking grow up when we use loops for (say) 10000 times. 

use numpy's:
1. **ufuncs**
1. **aggregations**
1. **broadcasting**
1. **slicing masking and fancy indexing**



In [14]:
## ufuncs => universal functions
# say to add 5 to each element of list in python, 

my_list= [1,2,4,5,91,-1]
new_list=[i+5 for i in my_list] # looping is required because adding 5 directly not possible here
print(new_list)
### numpy way:

import numpy as np
my_list= np.array(my_list)
new_list= my_list+5           #element wise addition happened here
print(new_list)

[6, 7, 9, 10, 96, 4]
[ 6  7  9 10 96  4]


In [7]:
#Note: numpy way is faster

a= list(range(100000))
%timeit sum(a)
import numpy as np
a= np.array(a)
%timeit np.sum(a)

975 µs ± 3.7 µs per loop (mean ± std. dev. of 7 runs, 1000 loops each)
94.8 µs ± 195 ns per loop (mean ± std. dev. of 7 runs, 10000 loops each)


#### **Broadcasting**

**Note**: A small array is broadcasted to a larger array.

In [9]:
import numpy as np
my_array= np.arange(70)
my_array.shape=(2,7,5)
print(my_array)

print(my_array.shape)   #Shape attribute
print(my_array.ndim)    # number of dimensions
print(my_array.size)   # number of elements
print(my_array.dtype)   # data type attribute

my_array*5 -2 

[[[ 0  1  2  3  4]
  [ 5  6  7  8  9]
  [10 11 12 13 14]
  [15 16 17 18 19]
  [20 21 22 23 24]
  [25 26 27 28 29]
  [30 31 32 33 34]]

 [[35 36 37 38 39]
  [40 41 42 43 44]
  [45 46 47 48 49]
  [50 51 52 53 54]
  [55 56 57 58 59]
  [60 61 62 63 64]
  [65 66 67 68 69]]]
(2, 7, 5)
3
70
int64


array([[[ -2,   3,   8,  13,  18],
        [ 23,  28,  33,  38,  43],
        [ 48,  53,  58,  63,  68],
        [ 73,  78,  83,  88,  93],
        [ 98, 103, 108, 113, 118],
        [123, 128, 133, 138, 143],
        [148, 153, 158, 163, 168]],

       [[173, 178, 183, 188, 193],
        [198, 203, 208, 213, 218],
        [223, 228, 233, 238, 243],
        [248, 253, 258, 263, 268],
        [273, 278, 283, 288, 293],
        [298, 303, 308, 313, 318],
        [323, 328, 333, 338, 343]]])

In [1]:
import numpy as np
left_mat= np.arange(6).reshape(2,3)
right_mat= np.arange(15).reshape(3,5)
# trying to find the inner product of the two matrix gives an error
# np.inner(left_mat,right_mat)

np.dot(left_mat,right_mat)  #check docstring for np.dot (shift+enter)


array([[ 25,  28,  31,  34,  37],
       [ 70,  82,  94, 106, 118]])

In [2]:
help (np.inner)

Help on built-in function inner in module numpy.core.multiarray:

inner(...)
    inner(a, b)
    
    Inner product of two arrays.
    
    Ordinary inner product of vectors for 1-D arrays (without complex
    conjugation), in higher dimensions a sum product over the last axes.
    
    Parameters
    ----------
    a, b : array_like
        If `a` and `b` are nonscalar, their last dimensions must match.
    
    Returns
    -------
    out : ndarray
        `out.shape = a.shape[:-1] + b.shape[:-1]`
    
    Raises
    ------
    ValueError
        If the last dimension of `a` and `b` has different size.
    
    See Also
    --------
    tensordot : Sum products over arbitrary axes.
    dot : Generalised matrix product, using second last dimension of `b`.
    einsum : Einstein summation convention.
    
    Notes
    -----
    For vectors (1-D arrays) it computes the ordinary inner-product::
    
        np.inner(a, b) = sum(a[:]*b[:])
    
    More generally, if `ndim(a) = r > 0` and

In [4]:
a= np.arange(24).reshape(2,3,4)
print(a)
b= np.arange(4)
print(b)
np.inner(a,b)

[[[ 0  1  2  3]
  [ 4  5  6  7]
  [ 8  9 10 11]]

 [[12 13 14 15]
  [16 17 18 19]
  [20 21 22 23]]]
[0 1 2 3]


array([[ 14,  38,  62],
       [ 86, 110, 134]])